"""Initial schema

Revision ID: b39c61318166
Revises: 
Create Date: 2026-08-18 19:18:38.611728
"""
from alembic import op
import sqlalchemy as sa


revision = 'b39c61318166'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('record_hash')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_table('construction_objects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('permit_number', sa.String(length=64), nullable=False),
    sa.Column('permit_date', sa.String(length=20), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('cadastral_number', sa.String(length=64), nullable=False),
    sa.Column('developer', sa.Text(), nullable=False),
    sa.Column('contractor', sa.Text(), nullable=False),
    sa.Column('designer', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('planned_completion', sa.String(length=20), nullable=False),
    sa.Column('card', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('assigned_to', sa.String(length=64), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_construction_objects_assigned_to'), 'construction_objects', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_construction_objects_department'), 'construction_objects', ['department'], unique=False)
    op.create_index(op.f('ix_construction_objects_permit_number'), 'construction_objects', ['permit_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=200), nullable=False),
    sa.Column('position', sa.String(length=200), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('valid_until', sa.String(length=20), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('transitions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=60), nullable=False),
    sa.Column('started_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('documents_count', sa.Integer(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['construction_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_object_id'), 'analysis_runs', ['object_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('state_kind', sa.String(length=20), nullable=False),
    sa.Column('doc_kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('revision', sa.String(length=20), nullable=False),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('signature_status', sa.String(length=20), nullable=False),
    sa.Column('facts_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['construction_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_object_id'), 'documents', ['object_id'], unique=False)
    op.create_index(op.f('ix_documents_state_kind'), 'documents', ['state_kind'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('public_id', sa.String(length=20), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.String(length=32), nullable=False),
    sa.Column('transition', sa.String(length=4), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('structural_element', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('norm_refs', sa.JSON(), nullable=False),
    sa.Column('legal_refs', sa.JSON(), nullable=False),
    sa.Column('field_check', sa.Text(), nullable=False),
    sa.Column('documents_to_request', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('injection_suspected', sa.Boolean(), nullable=False),
    sa.Column('detector', sa.String(length=60), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['construction_objects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_code'), 'findings', ['code'], unique=False)
    op.create_index(op.f('ix_findings_object_id'), 'findings', ['object_id'], unique=False)
    op.create_index(op.f('ix_findings_priority_score'), 'findings', ['priority_score'], unique=False)
    op.create_index(op.f('ix_findings_public_id'), 'findings', ['public_id'], unique=False)
    op.create_index(op.f('ix_findings_run_id'), 'findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_transition'), 'findings', ['transition'], unique=False)
    op.create_table('finding_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_assessments_finding_id'), 'finding_assessments', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_assessments_finding_id'), table_name='finding_assessments')
    op.drop_table('finding_assessments')
    op.drop_index(op.f('ix_findings_transition'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_run_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_public_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_priority_score'), table_name='findings')
    op.drop_index(op.f('ix_findings_object_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_code'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_documents_state_kind'), table_name='documents')
    op.drop_index(op.f('ix_documents_object_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_analysis_runs_object_id'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_table('users')
    op.drop_index(op.f('ix_construction_objects_permit_number'), table_name='construction_objects')
    op.drop_index(op.f('ix_construction_objects_department'), table_name='construction_objects')
    op.drop_index(op.f('ix_construction_objects_assigned_to'), table_name='construction_objects')
    op.drop_table('construction_objects')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
